### ISSUE TITLE
Build fail on Xcode 13.4.1 

### ISSUE THREAD

**Issue by alanwnl** [XCharts-Team/XCharts-Demo#1]
Build fail on Xcode 13.4.1 

Ld /Users/alanwong/Library/Developer/Xcode/DerivedData/Unity-iPhone-glqqilhserzhnxhhfvnckldfkeed/Build/Products/ReleaseForRunning-iphoneos/UnityFramework.framework/UnityFramework normal (in target 'UnityFramework' from project 'Unity-iPhone')
    cd /Users/alanwong/Dropbox/HKU/Project-Face\ Tracking/Reference\ Projects/XCharts-Demo-master/iOS
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++ -target arm64-apple-ios10.0 -dynamiclib -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS15.5.sdk -L/Users/alanwong/Library/Developer/Xcode/DerivedData/Unity-iPhone-glqqilhserzhnxhhfvnckldfkeed/Build/Products/ReleaseForRunning-iphoneos -L/Users/alanwong/Dropbox/HKU/Project-Face\ Tracking/Reference\ Projects/XCharts-Demo-master/iOS/Libraries -F/Users/alanwong/Library/Developer/Xcode/DerivedData/Unity-iPhone-glqqilhserzhnxhhfvnckldfkeed/Build/Products/ReleaseForRunning-iphoneos -F/Users/alanwong/Dropbox/HKU/Project-Face\ Tracking/Reference\ Projects/XCharts-Demo-master/iOS/Frameworks/com.unity.ads/Plugins/iOS -filelist /Users/alanwong/Library/Developer/Xcode/DerivedData/Unity-iPhone-glqqilhserzhnxhhfvnckldfkeed/Build/Intermediates.noindex/Unity-iPhone.build/ReleaseForRunning-iphoneos/UnityFramework.build/Objects-normal/arm64/UnityFramework.LinkFileList -install_name @rpath/UnityFramework.framework/UnityFramework -Xlinker -rpath -Xlinker @executable_path/Frameworks -Xlinker -rpath -Xlinker @loader_path/Frameworks -Xlinker -map -Xlinker /Users/alanwong/Library/Developer/Xcode/DerivedData/Unity-iPhone-glqqilhserzhnxhhfvnckldfkeed/Build/Intermediates.noindex/Unity-iPhone.build/ReleaseForRunning-iphoneos/UnityFramework.build/UnityFramework-LinkMap-normal-arm64.txt -dead_strip -Xlinker -object_path_lto -Xlinker /Users/alanwong/Library/Developer/Xcode/DerivedData/Unity-iPhone-glqqilhserzhnxhhfvnckldfkeed/Build/Intermediates.noindex/Unity-iPhone.build/ReleaseForRunning-iphoneos/UnityFramework.build/Objects-normal/arm64/UnityFramework_lto.o -fembed-bitcode-marker -stdlib\=libc++ -fobjc-arc -fobjc-link-runtime -weak_framework CoreMotion -weak-lSystem -liPhone-lib -framework Security -framework MediaToolbox -framework CoreText -framework AudioToolbox -weak_framework AVFoundation -framework AVKit -framework CFNetwork -framework CoreGraphics -framework CoreMedia -weak_framework CoreMotion -framework CoreVideo -framework Foundation -framework OpenAL -framework OpenGLES -framework QuartzCore -framework SystemConfiguration -framework UIKit -liconv.2 -lil2cpp -framework UnityAds -framework StoreKit -framework AdSupport -framework CoreTelephony -weak_framework Metal -weak_framework GameController -Xlinker -dependency_info -Xlinker /Users/alanwong/Library/Developer/Xcode/DerivedData/Unity-iPhone-glqqilhserzhnxhhfvnckldfkeed/Build/Intermediates.noindex/Unity-iPhone.build/ReleaseForRunning-iphoneos/UnityFramework.build/Objects-normal/arm64/UnityFramework_dependency_info.dat -o /Users/alanwong/Library/Developer/Xcode/DerivedData/Unity-iPhone-glqqilhserzhnxhhfvnckldfkeed/Build/Products/ReleaseForRunning-iphoneos/UnityFramework.framework/UnityFramework

Undefined symbols for architecture arm64:
  "_Download", referenced from:
      _ChartHelper_Download_m8337555D4D46D91AC93167ACB00AABFEB9CF48B0 in XCharts.Runtime1.o
     (maybe you meant: UnityWebRequestProto<UnityWebRequestTransport, AtomicRefCounter, RedirectHelper, ResponseHelper, DownloadHandler, UploadHandler, CertificateHandler, HeaderHelper, AsyncOperation>::Job_DownloadHandlerOnCompleteContent(UnityWebRequestProto<UnityWebRequestTransport, AtomicRefCounter, RedirectHelper, ResponseHelper, DownloadHandler, UploadHandler, CertificateHandler, HeaderHelper, AsyncOperation>*), _DownloadHandler_t4A7802ADC97024B469C87FA454B6973951980EE9_marshal_com_cleanup , _DownloadHandler_t4A7802ADC97024B469C87FA454B6973951980EE9_marshal_com_back , _DownloadHandler_t4A7802ADC97024B469C87FA454B6973951980EE9_marshal_com , _DownloadHandler_t4A7802ADC97024B469C87FA454B6973951980EE9_1_0_0 , _DownloadHandler_ReceiveContentLength_mDE85EFD21A56A3AAC11316F2D726D85186A7B7D9 , _DownloadHandler_t4A7802ADC97024B469C87FA454B6973951980EE9_marshal_pinvoke , _DownloadHandler_ReceiveContentLengthHeader_mF9A65E375B0AB4BA8AE068C15DCE0059B55014C6 , _DownloadHandler_t4A7802ADC97024B469C87FA454B6973951980EE9_marshal_pinvoke_back , _DownloadHandler_t4A7802ADC97024B469C87FA454B6973951980EE9_marshal_pinvoke_cleanup , _DownloadHandler_t4A7802ADC97024B469C87FA454B6973951980EE9_0_0_0 , _ChartHelper_Download_m8337555D4D46D91AC93167ACB00AABFEB9CF48B0 )
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by alanwnl** [comment]
I comment out the "Download" in the ChartHelper.cs to workaround this issue.

        //[DllImport("__Internal")]
        //private static extern void Download(string base64str, string fileName);

**Comment by monitor1394** [comment]
XCharts has been fixed. It will be released to XCharts-Demo later.
```
#if UNITY_WEBGL
        [DllImport("__Internal")]
        private static extern void Download(string base64str, string fileName);
#endif
```
