### ISSUE TITLE
AccessFrom and Serie0

### ISSUE THREAD

**Issue by RustamMuhammadFathulloh** [XCharts-Team/XCharts-Demo#2]
Hi.
I am using Pie Chart, Line Chart and Heatmap for my project.
When I move the mouse over the charts, "Serie 0" and "Access From" appear. How can I change or remove these entries?

**Comment by monitor1394** [comment]
I'm not sure which problem you specifically mentioned.
Could you please provide more information, such as screenshot?

**Comment by RustamMuhammadFathulloh** [comment]
I am using this line Chart. When the mouse is moved over the points, the inscription Serie0 will appear.
![image](https://user-images.githubusercontent.com/98743553/218373488-3dff3171-5871-4785-820a-baf8d5a2c528.png)
Heatmap also has "Serie0".

In this Pie Chart, the entry "Access From" is visible.
![image](https://user-images.githubusercontent.com/98743553/218374714-9689c46e-db31-4d48-ad3a-d72980643b87.png)

How can I change the "Access From" and "Serie0" entries to something else?

**Comment by monitor1394** [comment]
Disable  `Tooltip`  componnent in inspector view.

**Comment by RustamMuhammadFathulloh** [comment]
Thank you for your help.

**Comment by monitor1394** [comment]
"Access From" and "Serie0" is the name of serie and your can also change it in serie inpector view.
